spring:
  application:
    name: accounts-service
  datasource:
    url: ${db_url:jdbc:postgresql://localhost:5432/accounts_db}
    username: ${db_username:postgres}
    password: ${db_password:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update
management:
  endpoints:
    web:
      exposure:
        include: "env"