spring:
  application:
    name: accounts-service
  datasource:
    url: ${AccSrvDB_url}
    username: ${AccSrvDB_username}
    password: ${AccSrvDB_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update
management:
  endpoints:
    web:
      exposure:
        include: "env"